services:
  - type: web
    name: ecowheel-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ecowheel_backend.wsgi
    envVars:
      - key: DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: your-service-name.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: ecowheel-db
          property: connectionString

databases:
  - name: ecowheel-db
    databaseName: ecowheel
    user: postgres