services:
  - type: web
    name: ecowheel
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn ecowheel.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
    
      - key: DATABASE_URL
        fromDatabase:
          name: ecowheel
          property: connectionString

databases:
  - name: ecowheel
    databaseName: ecowheel_database
    user: ecowheel_database_user
    plan: free