# Generated by Django 5.2.1 on 2025-05-22 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impact', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='impactstats',
            name='trees_planted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='impactstats',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='impact_stats', to=settings.AUTH_USER_MODEL),
        ),
    ]
