# Generated by Django 5.2.1 on 2025-05-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impact', '0002_impactstats_trees_planted_alter_impactstats_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactstats',
            name='communities_supported',
            field=models.IntegerField(default=0),
        ),
    ]
