# Generated by Django 5.2.1 on 2025-05-22 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitystory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='impactstats',
            name='user',
        ),
        migrations.DeleteModel(
            name='Tour',
        ),
        migrations.DeleteModel(
            name='CommunityStory',
        ),
        migrations.DeleteModel(
            name='ImpactStats',
        ),
    ]
