# Generated by Django 5.2.1 on 2025-06-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_tour_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
