# Generated by Django 5.2.1 on 2025-05-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='distance',
        ),
        migrations.AddField(
            model_name='bookings',
            name='group_size',
            field=models.IntegerField(default=1),
        ),
    ]
